let jokes = [
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some fish play piano? You can't tuna fish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "How does a penguin build its house? Igloos it together.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "I told my wife she was overreacting. She just stormed off, saying, 'I'm not speaking to you anymore!'",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a shoe made out of a banana? A slipper!",
    "How does a train eat? It goes chew, chew.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent!",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some fish play piano? You can't tuna fish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I told my wife she was overreacting. She just stormed off, saying, 'I'm not speaking to you anymore!'",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a shoe made out of a banana? A slipper!",
    "How does a train eat? It goes chew, chew.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent!",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "What's brown and sticky? A stick.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some fish play piano? You can't tuna fish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I told my wife she was overreacting. She just stormed off, saying, 'I'm not speaking to you anymore!'",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a shoe made out of a banana? A slipper!",
    "How does a train eat? It goes chew, chew.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent!",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "What's brown and sticky? A stick.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some fish play piano? You can't tuna fish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I told my wife she was overreacting. She just stormed off, saying, 'I'm not speaking to you anymore!'",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a shoe made out of a banana? A slipper!",
    "How does a train eat? It goes chew, chew.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent!",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "What's brown and sticky? A stick.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some fish play piano? You can't tuna fish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I told my wife she was overreacting. She just stormed off, saying, 'I'm not speaking to you anymore!'",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a shoe made out of a banana? A slipper!",
    "How does a train eat? It goes chew, chew.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent!",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "What's brown and sticky? A stick."
];

// To access the jokes, you can use jokes[0], jokes[1], and so on.
let cat = document.getElementById("catmeme").style.opacity = ".01";
cat = document.getElementById("catmeme").muted = true;

let putjoke = () => {
    let a = Math.floor(Math.random() * jokes.length)
    let main = document.getElementById("joker");
    main.innerHTML = jokes[a];
    let j = jokes.pop(a - 1, a);
    console.log(j)

    console.log(a, jokes.length)
    if (jokes.length == 0) {
        main.innerHTML = "You readed upto 100 jokes , Database is limited"
        let cat = document.getElementById("catmeme").style.opacity = "1"
        cat = document.getElementById("catmeme").muted = false;
    }
}
